Also run CI tests with more features.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -122,10 +122,16 @@ jobs:
           cargo nextest run --workspace --cargo-profile ci
           cargo test --doc --workspace --profile ci
 
-  coverage:
+  test-workspace-features:
     needs: basics
-    name: code coverage
-    runs-on: ubuntu-latest
+    name: test workspace
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os:
+          - windows-latest
+          - ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
         with:
@@ -135,12 +141,6 @@ jobs:
         uses: dtolnay/rust-toolchain@stable
         with:
           toolchain: ${{ env.rust_stable }}
-          components: llvm-tools-preview
-
-      - name: Install cargo-llvm-cov
-        uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-llvm-cov
 
       - name: Install cargo-nextest
         uses: taiki-e/install-action@v2
@@ -148,25 +148,61 @@ jobs:
           tool: cargo-nextest
 
       - uses: Swatinem/rust-cache@v2
-      - name: Generate code coverage
-        run: |
-          cargo llvm-cov nextest --cargo-profile ci \
-            --package diskann-wide \
-            --package diskann-vector \
-            --package diskann-quantization \
-            --package diskann \
-            --package diskann-linalg \
-            --package diskann-utils \
-            --package diskann-disk \
-            --lcov --output-path lcov.info
 
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v4
-        with:
-          files: lcov.info
-          fail_ci_if_error: false
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      - name: test workspace with nextest
+        run: |
+          set -euxo pipefail
+          cargo nextest run --workspace --cargo-profile ci \
+            --features \
+              virtual_storage,bf_tree,spherical-quantization,product-quantization,tracing,experimental_diversity_search
+
+          cargo test --doc --workspace --profile ci
+
+  # coverage:
+  #   needs: basics
+  #   name: code coverage
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         lfs: true
+
+  #     - name: Install Rust ${{ env.rust_stable }}
+  #       uses: dtolnay/rust-toolchain@stable
+  #       with:
+  #         toolchain: ${{ env.rust_stable }}
+  #         components: llvm-tools-preview
+
+  #     - name: Install cargo-llvm-cov
+  #       uses: taiki-e/install-action@v2
+  #       with:
+  #         tool: cargo-llvm-cov
+
+  #     - name: Install cargo-nextest
+  #       uses: taiki-e/install-action@v2
+  #       with:
+  #         tool: cargo-nextest
+
+  #     - uses: Swatinem/rust-cache@v2
+  #     - name: Generate code coverage
+  #       run: |
+  #         cargo llvm-cov nextest --cargo-profile ci \
+  #           --package diskann-wide \
+  #           --package diskann-vector \
+  #           --package diskann-quantization \
+  #           --package diskann \
+  #           --package diskann-linalg \
+  #           --package diskann-utils \
+  #           --package diskann-disk \
+  #           --lcov --output-path lcov.info
+
+  #     - name: Upload coverage to Codecov
+  #       uses: codecov/codecov-action@v4
+  #       with:
+  #         files: lcov.info
+  #         fail_ci_if_error: false
+  #       env:
+  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
   # miri:
   #   needs: basics
